### ISSUE TITLE
Editing index.js.

### ISSUE THREAD

**Issue by psykosonic** [atmoner/nodeCrypto#1]
I have completed the installation of the server correctly, my only issue is editing the first variable of Index.js. What is it I need to do? 

The first line is
` // Compil`

 should this be
` // Compile? `

`Please excuse presumably what is a simple issue, I have very little experience within java-script mainly just python and some C++. 
Thanks.

**Comment by atmoner** [comment]
@psykosonic Sorry for waiting...  

This project is not completely finished but normally it works.
Many things are written in raw but I will coriate this quickly.
The only variables to edit are this:

```
const privateKey = 'myTotalySecretKey';
const websitePath = '/var/www/html/';
const serverCC = 'http://localhost/serveur/?page=insert'; //TODO: check ssl
const openReward = false;
```

1. privateKey: your key to encrypt/decrypt
2. websitePath: is the folder to encrypt
3. serverCC: is server install part
4. openReward: is opening reward (but not finished yet)
